### ISSUE TITLE
WLAN disconnecting from switch

### ISSUE THREAD

**Issue by bonicb** [i3roly/glibc_ddwrt#20]
I have tested the last 3 releases on my dir-1760 and am running in to the same issue.

I erase the nvram and setup dd-wrt in ap mode following this guide,
https://wiki.dd-wrt.com/wiki/index.php/Wireless_access_point

Everything is fine until randomly i can no longer reach devices on the lan. I can connect to the dd-wrt web ui via wifi but not from the lan ports.

The only device on the wifi is my android phone and the lan goes to my main switch, (router is pfsense).

Any help would be much appreciated.

**Comment by i3roly** [comment]
I’m not tech support Man.

You need to tell me which build number this apparent issue started in, and which one it apparently was working.

Keep in mind last time you listed an apparent issue with VAPs, you did a reset and everything worked again.

I have not touched any of the dd-wrt code in some time. All I did was update certain programs, libraries or the build system compiler. So I doubt this apparent problem has do with those.

On Sep 24, 2023, at 4:24 AM, bonicb ***@***.***> wrote:

﻿

I have tested the last 3 releases on my dir-1760 and am running in to the same issue.

I erase the nvram and setup dd-wrt in ap mode following this guide,
https://wiki.dd-wrt.com/wiki/index.php/Wireless_access_point

Everything is fine until randomly i can no longer reach devices on the lan. I can connect to the dd-wrt web ui via wifi but not from the lan ports.

The only device on the wifi is my android phone and the lan goes to my main switch, (router is pfsense).

Any help would be much appreciated.

**Comment by bonicb** [comment]
Thanks for your work, really appreciate it.
Im currently using using the latest build from your repo.
This has been an issue since changing from stock fw. (last 3 builds).

I have tried factory reset and reflashing with recovery ui.

I might try clearing nvram again and put this router on its own subnet to see if that changes anything.

Thanks for your time.

**Comment by i3roly** [comment]
You should try an even earlier build to see if this issue is still there. It probably is.

I’ll leave this open. Maybe @castlecaptain or @tesluh can help you. I can’t because I am not a hardcore network guy lol.

I need someone to breakdown exactly how to trigger the issue.

Thanks,
Gagan

On Sep 24, 2023, at 5:16 AM, bonicb ***@***.***> wrote:

﻿

Thanks for your work, really appreciate it.
Im currently using using the latest build from your repo.
This has been an issue since changing from stock fw. (last 3 builds).

I have tried factory reset and reflashing with recovery ui.

I might try clearing nvram again and put this router on its own subnet to see if that changes anything.

Thanks for your time.

**Comment by bonicb** [comment]
I have done another nvram clear and have touched no default settings. Just set a password for the ui and ssid. Ive plugged the wan into my main router/switch.
Im wondering if there is an issue cause by switching the operating mode from gateway to router. From what i can understand is that I can keep it in gateway mode and not plug anything into the wan port so I will give that a try if I get not crashes after a couple days.

To me, it seems that sometging is causing the switch to stop working as everything else seems ok. Will report back after some more testing to try and narrow down what is happening.

**Comment by CastleCaptain** [comment]
i am using the most recent versions of Gagan's DD-WRT variant router firmware on both a DIR-882 and on a DIR-3040. These are both running in a hardwired access point mode using the setup described in "Normal Version (Same Subnet)" of the DD-WRT help article that you linked. I use the LAN ports to interconnect to the main routers as it is not clear to me if the WAN port when disabled works as a LAN port. Also, I use DHCP Reservations on the main routers to assign the IP addresses and custom hostnames to their respective MAC addresses in addition to the static IP addresses assigned when you setup the DLInk routers as DD-WRT access points.
Sorry I cannot offer more than this. I am not a network guru just a longtime user.

**Comment by bonicb** [comment]
Thanks for thereply @CastleCaptain
Ive been on default settings (using the dir 1760 as a gateway for my main router) for a few days now without issue. I will slowly change settimgs and see what causes the disconnecting. My understanding is that you can no longer assign thr wan port to the switch anymore as it caused issues with some hardware.

**Comment by nikolatesluh** [comment]
@bonicb i am into networking, however for me to suggest anything, i need you to specify you network and hardware configuration to the  last T, even if it means you have changed an ethernet cable or  power adapter. Map it down in two ways, one, when your configuration was working, which i assume was on the stock dlink firmware, and second, after flashing ddwrt. once i get this information we can start diagnosing.

**Comment by i3roly** [comment]
btw @nikolatesluh @CastleCaptain HOW COME NONE OF YOU REPORTED THAT HTTPD DIDN'T WORK SINCE 54491? LOL. i fixed it now because one of my asshole "friends" decided to send my router some death packet, forcing me to give up my 300 days uptime and notice this issue. next push will have it fixed. rolled back all of the updates since 54491

**Comment by nikolatesluh** [comment]
im on rV54842M and everything works normally for me ? honestly i haven't updated in a while because everything just works, or am i missing something? except my 5GHz not connecting sometimes i never bothered, i have a bunch of omada AP's  i got from office i thought ill revamp my network with, but i just love your outlook with each update i decided to stick all of them in a box and shelve it xD ill go ahead and update to the latest f/w once you give me the green  signal xD 

> btw @nikolatesluh @CastleCaptain HOW COME NONE OF YOU REPORTED THAT HTTPD DIDN'T WORK SINCE 54491? LOL. i fixed it now because one of my asshole "friends" decided to send my router some death packet, forcing me to give up my 300 days uptime and notice this issue. next push will have it fixed. rolled back all of the updates since 54491

**Comment by i3roly** [comment]
If you're on an882 or 878 or whatever the latest build is fine. Looking into the 3040/2640 since @castlecaptain says it doesn't work. I think I forgot to resize the mtd for those builds since the fw got bigger                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: TesluhSent: Monday, 6 May 2024 10:39 AMTo: i3roly/glibc_ddwrtReply To: i3roly/glibc_ddwrtCc: gagan sidhu; State changeSubject: Re: [i3roly/glibc_ddwrt] WLAN disconnecting from switch (Issue #20)
im on rV54842M and everything works normally for me ? honestly i haven't updated in a while because everything just works, or am i missing something? except my 5GHz not connecting sometimes i never bothered, i have a bunch of omada AP's  i got from office i thought ill revamp my network with, but i just love your outlook with each update i decided to stick all of them in a box and shelve it xD ill go ahead and update to the latest f/w once you give me the green  signal xD

btw @nikolatesluh @CastleCaptain HOW COME NONE OF YOU REPORTED THAT HTTPD DIDN'T WORK SINCE 54491? LOL. i fixed it now because one of my asshole "friends" decided to send my router some death packet, forcing me to give up my 300 days uptime and notice this issue. next push will have it fixed. rolled back all of the updates since 54491


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/i3roly/glibc_ddwrt/issues/20#issuecomment-2096466348",
"url": "https://github.com/i3roly/glibc_ddwrt/issues/20#issuecomment-2096466348",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
