### ISSUE TITLE
testing Hardware NAT for dir-882

### ISSUE THREAD

**Issue by tsl0922** [i3roly/glibc_ddwrt#21]
This is my dd-wrt build scripts and patches repo: https://github.com/tsl0922/DD-WRT

I've added Hardware NAT support for mt7621, it's working for my device (k2p), but I don't have a dir-882 router hardware to test it.

`WAN` to `5G` speed test result (K2P, with 1xMT7615 & DBDC Mode):

![image](https://github.com/i3roly/glibc_ddwrt/assets/1680515/e7681fdc-9f8d-4ed8-9fd6-4517c1c93350)

You need to flash a dd-wrt official firmware first, then upgrade with the firmware from https://github.com/tsl0922/DD-WRT/releases

**WARNING:** YOU MAY BRICK YOUR ROUTER, MAKE SURE YOU KNOW HOW TO RESTORE FROM U-BOOT BEFORE TRYING IT.

**Comment by i3roly** [comment]
I'm confused sir.

What are you asking of me? I use hardware Nat and it works for sure. I get max throughput on my devices. My 2019 macbook pro 16" on ventura was hitting over 600mbps. In catalina it's about 500 so I suspect speed is limited by my software stack.

The short answer: of course hardware Nat works lol. I know the feeling once you discover its functionality, as it doubles throughput.

This is why I scoff at mt76 and will continue to do so.

Can you believe most of the hardware Nat code is over 15 years old? That, in my opinion, is the Everyday Genius Mediatek thinks it has, but really it's all RALINK aka RealTek.

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Shuanglei Tao
Sent: Monday, 2 October 2023 8:20 AM
To: i3roly/glibc_ddwrt
Reply To: i3roly/glibc_ddwrt
Cc: Subscribed
Subject: [i3roly/glibc_ddwrt] testing Hardware NAT for dir-882 (Issue #21)


This is my dd-wrt build scripts and patches repo: https://github.com/tsl0922/DD-WRT

I've added Hardware NAT support for mt7621, it's working for my device (k2p), but I don't have a dir-882 router hardware to test it.

You need to flash a dd-wrt official firmware first, then upgrade with the firmware from https://github.com/tsl0922/DD-WRT/releases

WARNING: YOU MAY BRICK YOUR ROUTER, MAKE SURE YOU KNOW HOW TO RESTORE FROM U-BOOT BEFORE TRYING IT.

**Comment by i3roly** [comment]
Oh I see

I should change that. I used to use blogic's hwnat mtk ethernet driver but it doesn't provide wlan acceleration. Now I actually use ra hwnat with raeth.

There is a way to do it (apparently) with blogic's hwnat, I would look at the mtk-eth driver used by @paldier and @hanwckf.

It's ugly though. You have to hard code all interfaces into the dts. They're not detected automatically. But it apparently works fine.

‎It's a modified version of blogic's hwnat driver made by Mediatek.

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Shuanglei Tao
Sent: Tuesday, 3 October 2023 7:59 AM
To: i3roly/glibc_ddwrt
Reply To: i3roly/glibc_ddwrt
Cc: gagan sidhu; Comment
Subject: Re: [i3roly/glibc_ddwrt] testing Hardware NAT for dir-882 (Issue #21)


How do you make BLOGIC's Hardware NAT for MT7621 devices<https://github.com/openwrt/openwrt/commit/424a9ae128bd2045cd4bfd6e3229f2529d150a25> work for ethernet -> wlan? The commit message says Supported are regular ethernet->ethernet connections.

**Comment by tsl0922** [comment]
OK, we're doing the same thing.

I'm using the raeth driver too, tried the new mtk_hnat driver, but it doesn't work well on 4.14 kernel (low throughput).

**Comment by i3roly** [comment]
raeth driver works 100% with ra hwnat

make sure your mt_wifi driver code in rt_linux.c has the right interface hook.

also make sure you're using the right version of ra hwnat. I used the one from @paldier which has wifi_new_arch flag and also fast_nat macro compilation flags.

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Shuanglei Tao
Sent: Tuesday, 3 October 2023 8:22 AM
To: i3roly/glibc_ddwrt
Reply To: i3roly/glibc_ddwrt
Cc: gagan sidhu; Comment
Subject: Re: [i3roly/glibc_ddwrt] testing Hardware NAT for dir-882 (Issue #21)‎


OK, we're doing the same thing.

I'm using the raeth driver too, tried the new mtk_hnat driver, but it doesn't work well on 4.14 kernel (low throughput).

**Comment by i3roly** [comment]
I should also add that it may take some effort. I remember originally I had the same issue as you but I sat down and went through all the code to fix it.

Took quite a bit of time. The summary of my efforts is given in the direction I provided in my previous comment.

Sent from my BlackBerry 10 smartphone on the Rogers network.

**Comment by i3roly** [comment]
while i congratulate you, this isn't the place to ask me how to make your build better lol. sorry.

i don't want to steal your thunder, but: while you did "do it" (build DD-WRT) in some sense, i note that your approach is not what the public would consider "having built DD-WRT". 

you simply took all of the DD-WRT system programs and it works for your specific configuration. but this is not how it is done. as brainslayer continually builds and changes things, you will see what i mean.

i should note: i have no trouble making builds for other boards. in fact, i had one for the TP-LINK AX50 (lantiq) but there is no functional wifi driver, so it is DOA.

anyways, congratulations but remember: there are no shortcuts in life. your approach works, and congratulations on that.

but you will see my friend, how quickly this functional build you currently have, can break.

mine does not break. so as far as i'm concerned, i'm still the only person standing. not even kong (bless his soul) stood as long as i have, and BS gave him the build tree.

no one aside from kong has built DD-WRT successfully whilst being faithful to the svn revision number, aside from me (because kong moved to openwrt since it was getting too hard for him lol).

again, just remember: being perceived as elite means you don't take shortcuts.

nice job though.

**Comment by i3roly** [comment]
deleting due to self-promotion and inappropriate acclamation of a coveted milestone in the networking kernel community.
