### ISSUE TITLE
Sir I am using 2640


### ISSUE THREAD

**Issue by captain-delsagade** [i3roly/glibc_ddwrt#22]
Qos not working .

**Comment by i3roly** [comment]
This gives me nothing useful to help try and fix the issue.

I'm not sure if you can QoS on this driver. Probably can on mt76. Try the latest openwrt and let me know if you can get fast downloads.

@tesluh @castlecaptain have either of you tried any recent mt76 builds? I'm thinking the latest updates ‎are just fluff but really I'm not sure if shit like qos will work with the mt_wifi driver. I haven't tried to use it though.


Sent from my BlackBerry 10 smartphone on the Rogers network.
From: captain-delsagade
Sent: Thursday, 28 December 2023 2:15 PM
To: i3roly/glibc_ddwrt
Reply To: i3roly/glibc_ddwrt
Cc: Subscribed
Subject: [i3roly/glibc_ddwrt] Sir I am using 2640 (Issue #22)


Qos not working .

**Comment by i3roly** [comment]
I just checked and it's possible the issue is the outdated svqos and svqos2 scripts in usr/sbin.

I've updated them on my side and will push a new firmware when assfuck is done spinkicking with the new ssh receive window option. If this doesn't solve the problem, it's likely due to the driver because I have qos enabled in both the hardware NAT and WIFI so it should work.

Thanks for bringing this to my attention.

Sent from my BlackBerry 10 smartphone on the Rogers network.

**Comment by captain-delsagade** [comment]
Sir 1 more thing ..
Whenever  I just click through the menus, options tabs it take 1-2 seconds to do the response...
In other words the web ui is very slow and less responsive.
Dir_2640 A1

**Comment by i3roly** [comment]
don't get carried away, noob.

there's nothing wrong with the webgui. it's probably because you're from india.

others would have reported this by now.

**Comment by CastleCaptain** [comment]
I do not use QOS so I cannot comment on whether it works or not. As far
WebUI responsiveness is concerned, I don't find it much different than
regular DD-WRT and if it is slower it it is not enough of an issue to
impede usage.
