### ISSUE TITLE
Not booting after install 2640

### ISSUE THREAD

**Issue by abhijitghosh108** [i3roly/glibc_ddwrt#23]
i install the file from dlink recovery gui but not boots

**Comment by i3roly** [comment]
Which file are you using?Try an older one from commit history too.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: AbhijitSent: Monday, 29 April 2024 2:19 PMTo: i3roly/glibc_ddwrtReply To: i3roly/glibc_ddwrtCc: SubscribedSubject: [i3roly/glibc_ddwrt] Not booting after install 2640 (Issue #23)
i install the file from dlink recovery gui but not boots

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/i3roly/glibc_ddwrt/issues/23",
"url": "https://github.com/i3roly/glibc_ddwrt/issues/23",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by i3roly** [comment]
I won't be able to fix the problem unless you flash older ones (assuming you're using the right file) so I can find the problem between the older version to the newest. But there shouldn't be any problem. Others would have reported it.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: Gagan SidhuSent: Thursday, 2 May 2024 9:03 AMTo: AbhijitSubject: Re: [i3roly/glibc_ddwrt] Not booting after install 2640 (Issue #23)                                                                                      Which file are you using?Try an older one from commit history too.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: AbhijitSent: Monday, 29 April 2024 2:19 PMTo: i3roly/glibc_ddwrtReply To: i3roly/glibc_ddwrtCc: SubscribedSubject: [i3roly/glibc_ddwrt] Not booting after install 2640 (Issue #23)
i install the file from dlink recovery gui but not boots

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/i3roly/glibc_ddwrt/issues/23",
"url": "https://github.com/i3roly/glibc_ddwrt/issues/23",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
